### ISSUE TITLE
训练和评测数据是否可以开源？

### ISSUE THREAD

**Issue by wangzaistone** [winninghealth/WiNGPT2#1]
您好，请问相关的训练数据和评测数据是否可以开源？模型是基于qianwen-7B训练的？

**Comment by winninghealth** [comment]
训练数据暂时没有计划公开，测评数据采用的是公开的数据集：https://cevalbenchmark.com/
后续我们会更新更多的测试结果和测试数据。

**Comment by cherishleon** [comment]
想问问微调代码会公布吗

**Comment by cherishleon** [comment]
> 训练数据暂时没有计划公开，测评数据采用的是公开的数据集：https://cevalbenchmark.com/ 后续我们会更新更多的测试结果和测试数据。

想问问微调代码会公布吗

**Comment by winninghealth** [comment]
开源项目中包含微调代码的太多了，WiNGPT2是通用的模型架构因此只要可以用hf加载的都支持。如果一定要推荐一个，可以看下https://github.com/lm-sys/FastChat

**Comment by cherishleon** [comment]
> 开源项目中包含微调代码的太多了，WiNGPT2是通用的模型架构因此只要可以用hf加载的都支持。如果一定要推荐一个，可以看下https://github.com/lm-sys/FastChat
get thanks

**Comment by cherishleon** [comment]
> 开源项目中包含微调代码的太多了，WiNGPT2是通用的模型架构因此只要可以用hf加载的都支持。如果一定要推荐一个，可以看下https://github.com/lm-sys/FastChat

get thanks

**Comment by LiangYong1216** [comment]
> > 开源项目中包含微调代码的太多了，WiNGPT2是通用的模型架构因此只要可以用hf加载的都支持。如果一定要推荐一个，可以看下https://github.com/lm-sys/FastChat
> 
> get thanks

微调成功了吗？可否分享一下微调代码呢
