### ISSUE TITLE
pretrain和finetune阶段的 tokenized format

### ISSUE THREAD

**Issue by nlp4whp** [winninghealth/WiNGPT2#10]
您好，我想了解下您在 pretrain 和 finetune 阶段的tokenized格式，特别是special tokens的添加

因为您是基于`Qwen-7B`(而非`Qwen-7B-Chat`)，所以按我理解，您是：

- pretrain: 仅用到`eos_token`, 也就是`<|endoftext|>`
- finetune: 此阶段才加入`'<|im_start|>user',  '<|im_start|>assistant'`等多个special tokens（和qwen-chat的chatml格式保持一致），然后基于50W指令做full-finetune

因为我基于Base，用chatml格式做LoRA微调，最后会生成乱码，猜测是因为数据/训练不够，如果那些特殊符号是finetune阶段才加入的，应该我自己设计其他格式也是可行的

**Comment by winninghealth** [comment]
pretrain阶段您的理解是对的，special token仅使用 <|endoftext|>

至于 finetune阶段，此阶段我们并没有使用qwen-chat的special token；我们使用的时候自定义范式----User:[空格]content<|endoftext|>\n[空格]Assistant:

所以您针对basemodel 使用自己设计的其他格式都是可行的，一般来说结束符统一就可以。

我们在早期测试模型的时候，也使用过几百条进行自定义格式微调，模型也能够很好的回答一部分问题。所以您的乱码问题，可能是训练不够带来的。

**Comment by nlp4whp** [comment]
> pretrain阶段您的理解是对的，special token仅使用 <|endoftext|>
> 
> 至于 finetune阶段，此阶段我们并没有使用qwen-chat的special token；我们使用的时候自定义范式----User:[空格]content<|endoftext|>\n[空格]Assistant:
> 
> 所以您针对basemodel 使用自己设计的其他格式都是可行的，一般来说结束符统一就可以。
> 
> 我们在早期测试模型的时候，也使用过几百条进行自定义格式微调，模型也能够很好的回答一部分问题。所以您的乱码问题，可能是训练不够带来的。

🙏多谢多谢
