### ISSUE TITLE
一些问题拒绝回答

### ISSUE THREAD

**Issue by SiriusWy** [winninghealth/WiNGPT2#15]
感谢分享，我测试了一些问题，很多拒绝回答，是不是对齐的时候有点“过头”啊
![image](https://github.com/winninghealth/WiNGPT2/assets/9431785/93010c7e-08fa-46d6-906a-b8997362a2f5)

**Comment by X-jun-0130** [comment]
感谢提醒，我们已注意到该问题；并且已经在新模型中改善了该问题。
