### ISSUE TITLE
[DOC] Some bugs in README.md

### ISSUE THREAD

**Issue by MING-ZCH** [winninghealth/WiNGPT2#16]
README.md文件存在部分错误，为保证专业性和美观，建议修改：
* 1
<img width="449" alt="92f9711ebe4cc0301e02136080fb2c7" src="https://github.com/winninghealth/WiNGPT2/assets/119648793/0e84394b-e19e-43fc-b1b3-ec22da1e9a03">

* 2
<img width="272" alt="1602fb61d311616f1f9c453789b401d" src="https://github.com/winninghealth/WiNGPT2/assets/119648793/1d73b1c3-fb82-47a4-b688-b5a630387dbc">

* 3
![image](https://github.com/winninghealth/WiNGPT2/assets/119648793/f2c536a8-a54d-4a20-8f85-f2287cf338d9)

**Comment by winninghealth** [comment]
谢谢建议，已经更新文档。
