### ISSUE TITLE
WiNGPT2-7B-Chat开源模型使用model.chat方法报错

### ISSUE THREAD

**Issue by fengxuefx** [winninghealth/WiNGPT2#2]
参考官方提供的代码，同时结合阿里千问官方代码，写的如下测试代码：
`
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig

model_path = "/*/WiNGPT2-7B-Chat"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True)
model = model.eval().to(device)

generation_config = GenerationConfig.from_pretrained(model_path, trust_remote_code=True)

response, history = model.chat(tokenizer, "你好", history=None)
print(response)
response, history = model.chat(tokenizer, "浙江的省会在哪里？", history=history)
print(response)
response, history = model.chat(tokenizer, "它有什么好玩的景点", history=history)
print(response)
`
修改generation_config.json文件如下：根据报错信息，只修改了chat_format参数。
`
{
  "chat_format": "chatml",
  "do_sample": true,
  "eos_token_id": 151643,
  "max_new_tokens": 512,
  "pad_token_id": 151643,
  "stop_words_ids": [
    [
      151643
    ]
  ],
  "top_k": 0,
  "top_p": 0.8,
  "transformers_version": "4.28.1"
}
`
报错显示参数不对：
`
Traceback (most recent call last):
  File "/***/test.py", line 29, in <module>
    ponse, history = model.chat(tokenizer, "你好", history=None)
  File "/root/.cache/huggingface/modules/transformers_modules/WiNGPT2-7B-Chat/modeling_qwen.py", line 1003, in chat
    max_window_size = generation_config.max_window_size
AttributeError: 'GenerationConfig' object has no attribute 'max_window_size'
`
各个文件都是官方下载的，如果版本都对应的话，感觉不应该会出现没有这个参数这种错误。请问是我哪里操作不对吗？

**Comment by fengxuefx** [comment]
找到原因了，[https://huggingface.co/winninghealth/WiNGPT2-7B-Chat/tree/main](url) 这个链接里面的generation_config.json文件不是千问最新的版本，最新版本里面有这个参数，更新下就可以了。

**Comment by winninghealth** [comment]
可以看我们的[推理示例](https://github.com/winninghealth/WiNGPT2/tree/main#%E6%8E%A8%E7%90%86)：
```
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig

model_path = "WiNGPT2-7B-Chat"

tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True)
model = model.eval()

generation_config = GenerationConfig(
  repetition_penalty=1.1,
  max_new_tokens=1024
)

text = 'User: WiNGPT, 你好<|endoftext|>\n Assistant: '
inputs = tokenizer.encode(text, return_tensors="pt").to(device)
outputs = model.generate(inputs, generation_config=generation_config)
output = tokenizer.decode(outputs[0])
response = output.replace(inputs, '')

## 输出结果：你好！今天我能为你做些什么？<|endoftext|>
```
modeling_qwen.py文件中的chat代码我们没有使用和测试，经过训练原始的参数可能会与WiNGPT2模型有出入，我们建议使用我们提供的示例参数进行测试。

**Comment by fengxuefx** [comment]
嗯，示例代码稍微修改下可以跑通，但是比较简单，能不能提供个类似qwen的web_demo.py的带前端的脚本呢？
我正在测试qwen官方的web_demo.py脚本能不能用这个模型

**Comment by winninghealth** [comment]
支持hf推理的web_gradio脚本开源的已经有很多了，事实上我们之前已经开源了一个相对完整的chatbot应用，感兴趣的话可以试试：https://github.com/winninghealth/KissChatbot

**Comment by fengxuefx** [comment]
> 支持hf推理的web_gradio脚本开源的已经有很多了，事实上我们之前已经开源了一个相对完整的chatbot应用，感兴趣的话可以试试：https://github.com/winninghealth/KissChatbot

好的，我去看看，谢谢你啦

**Comment by fengxuefx** [comment]
请问，我发现测试的时候，第一句”你好“，通常回答的结果很飘，比如
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/ad3af47c-ccc6-4d99-99e4-481156ed799d)
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/fcfade79-74d4-449d-9c6b-f2b2851e608f)
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/735fc325-25f3-4a0c-bc58-cc248c2d98c5)
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/1a15fd57-f0f0-4060-8a86-625b1cf95810)
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/c1fc81d4-cb3b-4049-b01f-9c6ebcc6e633)

，请问是我一些参数配置的不合适吗？

**Comment by winninghealth** [comment]
WiNGPT2-7B-Chat使用了自定义的输入输出格式：
使用时需遵循以下规则：
1. 用户角色：User/Assistant
2. 输入规范：User:[此处有空格]WiNGPT, 你好<|endoftext|>\n[此处有空格]Assistant:[此处有空格]；多轮按此规则进行拼接
3. 我们在解码时，使用repetition_penalty=1.1,max_new_tokens=1024，topk=30,topp=0.75 [可自由探索更佳解码方案]

你的上述错误，很明显的一个原因是输入不符合WiNGPT-7B-Chat的输入规范。

**Comment by fengxuefx** [comment]
> WiNGPT2-7B-Chat使用了自定义的输入输出格式： 使用时需遵循以下规则：
> 
> 1. 用户角色：User/Assistant
> 2. 输入规范：User:[此处有空格]WiNGPT, 你好<|endoftext|>\n[此处有空格]Assistant:[此处有空格]；多轮按此规则进行拼接
> 3. 我们在解码时，使用repetition_penalty=1.1,max_new_tokens=1024，topk=30,topp=0.75 [可自由探索更佳解码方案]
> 
> 你的上述错误，很明显的一个原因是输入不符合WiNGPT-7B-Chat的输入规范。

好的，我看下，谢谢

**Comment by fengxuefx** [comment]
> WiNGPT2-7B-Chat使用了自定义的输入输出格式： 使用时需遵循以下规则：
> 
> 1. 用户角色：User/Assistant
> 2. 输入规范：User:[此处有空格]WiNGPT, 你好<|endoftext|>\n[此处有空格]Assistant:[此处有空格]；多轮按此规则进行拼接
> 3. 我们在解码时，使用repetition_penalty=1.1,max_new_tokens=1024，topk=30,topp=0.75 [可自由探索更佳解码方案]
> 
> 你的上述错误，很明显的一个原因是输入不符合WiNGPT-7B-Chat的输入规范。

![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/ebe6df78-8d1f-43b6-9a7d-6fcc76102931)
你好，我想请问下，这样使用的时候，是把query按照上面多轮对话的拼接格式，把所有的history全部拼接到query里面传参给query，task_history参数为空吗？

**Comment by fengxuefx** [comment]
> WiNGPT2-7B-Chat使用了自定义的输入输出格式： 使用时需遵循以下规则：
> 
> 1. 用户角色：User/Assistant
> 2. 输入规范：User:[此处有空格]WiNGPT, 你好<|endoftext|>\n[此处有空格]Assistant:[此处有空格]；多轮按此规则进行拼接
> 3. 我们在解码时，使用repetition_penalty=1.1,max_new_tokens=1024，topk=30,topp=0.75 [可自由探索更佳解码方案]
> 
> 你的上述错误，很明显的一个原因是输入不符合WiNGPT-7B-Chat的输入规范。

![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/f0f4cf00-6c2a-469e-aa14-ab9c02b32c01)
请问，可以帮忙看下这个是什么问题吗？

**Comment by fengxuefx** [comment]
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/14a18028-7fb0-4bc7-b220-798d994da62f)
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/609d017d-6fea-46a9-9357-468af3cd4c7c)
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/162aafed-f762-4009-81b4-d08b33c182cb)
你好，请问可以帮忙看下哪里不对吗？

**Comment by fengxuefx** [comment]
> ![image](https://user-images.githubusercontent.com/89891025/273433126-14a18028-7fb0-4bc7-b220-798d994da62f.png) ![image](https://user-images.githubusercontent.com/89891025/273433160-609d017d-6fea-46a9-9357-468af3cd4c7c.png) ![image](https://user-images.githubusercontent.com/89891025/273433268-162aafed-f762-4009-81b4-d08b33c182cb.png) 你好，请问可以帮忙看下哪里不对吗？ 第一张是相关推理代码逻辑，第二章是结果，第三章是对应的日志打印。 query输入模型前，我按照你上面说的格式设置了。

模型是用的WinGPT2-7b-chat，然后generation_config.json配置是下面的格式：
`
{
  "chat_format": "chatml",
  "eos_token_id": 151643,
  "pad_token_id": 151643,
  "max_window_size": 6144,
  "max_new_tokens": 1024,
  "do_sample": true,
  "top_k": 30,
  "top_p": 0.75,
  "transformers_version": "4.31.0",
  "stop_words_ids": [
    [
      151643
    ]
  ],
  "num_beams": 1,
  "repetition_penalty": 1.1
}
`
读取方式是这个：
`
config = GenerationConfig.from_pretrained(
        args.checkpoint_path, trust_remote_code=True, resume_download=True,
    )
`

**Comment by fengxuefx** [comment]
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/4558a537-e0e7-4e96-9046-7c99eeeafd38)
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/2e30e9a8-b7a1-4e06-a99f-54acebb0c11d)
![image](https://github.com/winninghealth/WiNGPT2/assets/89891025/10250115-e283-4a0d-bc85-fcb48fd4df5d)

我按照上面发的多轮对话拼接规则把所有的历史对话都拼接到一个query里面，history参数传空，返回的结果更多都是带有User,Assistant这种结果呢？
我想确认的是，是我使用方式不对，还是这的确是模型存在的一些问题呢？麻烦帮忙解答一下，感谢。

**Comment by AppleJunJiang** [comment]
我有同样的问题，因为自定义的输入输出格式，导致官方的chat和chat_stream的断句都有问题，官方能给提供一个流式输出的案例么
