### ISSUE TITLE
WiNGPT2-Llama3-8B-Chat 问下微调路径？

### ISSUE THREAD

**Issue by wandouguo** [winninghealth/WiNGPT2#20]
WiNGPT2-Llama3-8B-Chat 问下是基于哪条路径得到的呢：
1、Llama3-8B-base+FT
2、Llama3-8B-Instruct+FT
3、Llama3-8B-base+CPT+SFT
4、Llama3-8B-Instruct+CPT+SFT

有经验推荐吗

**Comment by X-jun-0130** [comment]
3
