### ISSUE TITLE
啥时候会开源4bit量化模型和使用方法

### ISSUE THREAD

**Issue by AppleJunJiang** [winninghealth/WiNGPT2#3]

**Comment by winninghealth** [comment]
4bit量化方案请参照 https://github.com/PanQiWei/AutoGPTQ  【pip install auto-gptq optimum】
可自行对模型进行量化操作
量化后模型使用方法与原生一致

**Comment by AppleJunJiang** [comment]
AutoGPTQ量化后的模型，无法用AutoModelForCausalLM.from_pretrained加载（一直加载不执行model.eval()），只能用AutoGPTQForCausalLM.from_quantized加载，AutoGPTQForCausalLM特别慢，感觉和没量化一样。官方啥时候提供一下4bit模型吧，方便大家测试
cuda  117
torch  2.0.1+cu117

**Comment by winninghealth** [comment]
已经公开了
