### ISSUE TITLE
模型推理失败

### ISSUE THREAD

**Issue by houpanpan** [winninghealth/WiNGPT2#5]
模型加载一切都正常，但是最后报错为"Killed"
代码如下：

from transformers import AutoModelForCausalLM, AutoTokenizer

model_path = "WiNGPT2-7B-Chat"
device = "cuda"
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True).to(device)
model = model.eval()

text = 'User: WiNGPT, 你好<|endoftext|>\n Assistant: '
inputs = tokenizer.encode(text, return_tensors="pt").to(device)
outputs = model.generate(inputs, repetition_penalty=1.1, max_new_tokens=1024)
response = tokenizer.decode(outputs[0])
print(response)

报错如下：
“Killed”
 请解答。（最好可以把推理代码的运行依赖环境同步下，谢谢）

**Comment by winninghealth** [comment]
要求（Requirements）
python 3.8及以上版本
pytorch 1.12及以上版本，推荐2.0及以上版本
建议使用CUDA 11.4及以上（GPU用户、flash-attention用户等需考虑此选项）
pip install transformers>=4.28.1  tiktoken  einops

建议显存不低于16G
