### ISSUE TITLE
【评测结果】复现问题

### ISSUE THREAD

**Issue by houpanpan** [winninghealth/WiNGPT2#6]
请问github 的 readme 中的【评测结果】是在 7B 模型上的评估结果嘛，如果是，请问是哪一个版本呢（Base or Chat版本呢），如果是 Base 模型的版本，在模型评估的时候，有类似 Chat 版本的 prompt 工程策略吗？

**Comment by winninghealth** [comment]
评估的是7B-base模型

评估的样例形式如下：
以下是中国关于计算机网络考试的单项选择题，请选出其中的正确答案。
在802.3标准中，发送帧之前需要____

A. 等待冲突
B. 等待令牌
C. 监听介质
D. 接受一个帧

答案：

**Comment by houpanpan** [comment]
其他的参数设置和 readme 中的展示是保持一致的，对嘛？
比如：repetition_penalty=1.1, max_new_tokens=1024

**Comment by winninghealth** [comment]
repetition_penalty=1.1, max_new_tokens=256
 大部分题目会直接给出答案，极少量会生成长文，从时间考虑减少了生成长度。
