### ISSUE TITLE
在使用model.chat_stream(tokenizer, _query, history=_task_history, generation_config=config)的时候报错

### ISSUE THREAD

**Issue by AppleJunJiang** [winninghealth/WiNGPT2#7]
在使用model.chat_stream进行流式输出的时候，报错：
If you are directly using the model downloaded from Huggingface, please make sure you are using our "Qwen/Qwen-7B-Chat" Huggingface model (rather than "Qwen/Qwen-7B") when you call model.chat().
我们检测到您可能在使用预训练模型（而非chat模型）进行多轮chat，因为您当前在generation_config指定的chat_format，并未设置为我们在对话中所支持的"chatml"格式。
对比Qwen的generation_config.json文件发现你们的是 "chat_format": "raw"而不是 "chat_format": "chatml"
请问，要使用流式输出，应该怎么修改，有没有例子，直接修改成chatml可以运行，但是会输出很多无关的内容，估计是断句出了问题

**Comment by winninghealth** [comment]
WiNGPT-Chat的输入方式，并不与Qwen-Chat相同，请仔细阅读我们的文档

transformers中的TextIteratorStreamer函数支持流式输出

**Comment by AppleJunJiang** [comment]
已解决
