### ISSUE TITLE
推理

### ISSUE THREAD

**Issue by DecideToLeave** [winninghealth/WiNGPT2#9]
模型推理内容是加在User: WiNGPT, 你好<|endoftext|>\n Assistant: 之后吗

**Comment by winninghealth** [comment]
对的，如果需要进行多轮对话，模型推理内容加在Assistant:后面
如下：
"User: WiNGPT, 你好<|endoftext|>\n Assistant: 你好！今天我能为你做些什么？<|endoftext|>\n User: 你是谁？<|endoftext|>\n Assistant: "

**Comment by DecideToLeave** [comment]
OK，感谢
